<?php
// $Id$
/**
 * sparql.module - Enables the use of SPARQL queries with the RDF API.
 *
 * @author Arto Bendiken <http://bendiken.net/>
 * @copyright Copyright (c) 2007-2008 Arto Bendiken. All rights reserved.
 * @license GPL <http://creativecommons.org/licenses/GPL/2.0/>
 * @package sparql.module
 */

//////////////////////////////////////////////////////////////////////////////
// Core API hooks

/**
 * Implements hook_init().
 */
function sparql_init() {
  // Include sparql.inc to provide API to other modules.
  require_once drupal_get_path('module', 'sparql') . '/sparql.inc';
}

/**
 * Implements hook_help().
 */
function sparql_help($path, $arg = NULL) {
  switch ($path) {
    case 'admin/settings/sparql':
      return '<p>' . t('The sparql module provides an interface for other modules to perform sparql queries') . '</p>'; // TODO
  }
}


/**
 * Implements hook_menu().
 */
function sparql_menu() {
  return array(
    // Administer >> Site configuration >> SPARQL settings
    'admin/sparql/settings' => array(
      'title' => 'SPARQL settings',
      'description' => 'Settings for the SPARQL API.',
      'access arguments' => array('administer site configuration'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('sparql_admin_settings'),
      'file' => 'sparql.admin.inc',
    ),
  );
}