<?php

/**
 * Implements hook_menu().
 */
function sparql_endpoint_menu() {
  // @todo use access RDF data permission instead of access content.
  $items['sparql'] = array(
    'title' => 'SPARQL endpoint',
    'page callback' => 'sparql_endpoint_sparql_endpoint',
    'access arguments' => array('access content'),
  );
  $items['sparql_endpoint_index'] = array(
    'title' => 'Build RDF index',
    'page callback' => 'sparql_endpoint_index_rdf',
    'access arguments' => array('access content'),
  );
  return $items;
}

function sparql_endpoint_initialize($type = 'store') {
  $db = $GLOBALS['databases']['default']['default'];
  $config = array(
    /* db */
    'db_host' => $db['host'],
    'db_name' => $db['database'],
    'db_user' => $db['username'],
    'db_pwd' => $db['password'],
    /* store */
    'store_name' => 'sparql_endpoint_arc2',

    /* endpoint */
    'endpoint_features' => array(
      'select', 'construct', 'ask', 'describe',
      'load', 'insert', 'delete',
      'dump' /* dump is a special command for streaming SPOG export */
    ),
    'endpoint_timeout' => 60, /* not implemented in ARC2 preview */
    'endpoint_read_key' => '', /* optional */
    'endpoint_write_key' => 'somekey', /* optional */
    'endpoint_max_limit' => 500, /* optional */
  );

  /* instantiation */
  if ($type == 'endpoint') {
    $store = ARC2::getStoreEndpoint($config);
  }
  else {
    $store = ARC2::getStore($config);
  }
  if (!$store->isSetUp()) {
    $store->setUp();
  }
  return $store;
}

function sparql_endpoint_index_rdf() {
  // Instantiate the ARC2 local store.
  $store = sparql_endpoint_initialize();

  // Emtpy the local store.
  // FIXME optimize by doing this only when creating/saving a node.
  $store->reset();

  // Index all the nodes which are published.
  $query = db_select('node', 'n')->extend('PagerDefault')->extend('TableSort');
  $query->condition('n.status', 1);
  $ids = $query
    ->fields('n',array('nid'))
    ->limit(500)
    ->execute()
    ->fetchCol();

  foreach ($ids as $id) {
    $rdf = rdfx_get_rdf_model('node', $id);
    $store->insert($rdf->index, $rdf->uri);
  }

  // Index all the users.
  $query = db_select('users', 'u')->extend('PagerDefault')->extend('TableSort');
  $query->condition('u.uid', 0, '<>');
  $ids = $query
    ->fields('u', array('uid'))
    ->limit(500)
    ->execute()
    ->fetchCol();

  foreach ($ids as $id) {
    $rdf = rdfx_get_rdf_model('user', $id);
    $store->insert($rdf->index, $rdf->uri);
  }

  // Index all the terms.
  $query = db_select('taxonomy_term_data', 't')->extend('PagerDefault')->extend('TableSort');
  $ids = $query
    ->fields('t', array('tid'))
    ->limit(500)
    ->execute()
    ->fetchCol();

  foreach ($ids as $id) {
    $rdf = rdfx_get_rdf_model('taxonomy_term', $id);
    $store->insert($rdf->index, $rdf->uri);
  }

  return t('The RDF index of the site has been rebuilt. Browse to the <a href="@endpoint">SPARQL endpoint</a> to query it.', array('@endpoint' => url('sparql')));
}

function sparql_endpoint_sparql_endpoint() {
  // FIXME add all the ns in the default SPARQL query
  // patch to be committed to ARC2.
  $nss = rdf_get_namespaces();
  global $default_p;
  // @temp remove some less used prefixes.
  unset($nss['sioct']);
  unset($nss['rss']);
  $nss['site'] = url('', array('absolute' => TRUE));
  foreach($nss as $prefix => $ns) {
    $default_p .= "PREFIX $prefix: <" . $ns . ">\n";
  }

  // Instantiate the ARC2 SPARQL endpoint.
  $ep = sparql_endpoint_initialize('endpoint');
  $ep->go();
}

/**
 * Implements hook_node_insert().
 */
function sparql_endpoint_node_insert($node) {
  // Instantiate the ARC2 local store.
  $store = sparql_endpoint_initialize();

  // Build RDF model for the node.
  $rdf = rdfx_get_rdf_model('node', $node->nid);

  // Add node to the store.
  $store->insert($rdf->index, $rdf->uri);
}

/**
 * Implements hook_node_update().
 */
function sparql_endpoint_node_update($node) {
  // Instantiate the ARC2 local store.
  $store = sparql_endpoint_initialize();

  // Build RDF model for the node.
  $rdf = rdfx_get_rdf_model('node', $node->nid);

  // Cleans out the graph and reindex the node.
  $store->query('DELETE FROM <' . $rdf->uri . '>');
  $store->insert($rdf->index, $rdf->uri);
}
